---
cluster:
  hosts:
    play1.playcluster.plone.org:
      ansible_user: root
      ansible_host: play1.playcluster.plone.org
      host: play1
      hostname: play1.playcluster.plone.org
      swarm_node:
        labels:
          type: manager
          env: production
    play2.playcluster.plone.org:
      ansible_user: root
      ansible_host: play2.playcluster.plone.org
      host: play2
      hostname: play2.playcluster.plone.org
      swarm_node:
        labels:
          type: worker
          env: production
    play3.playcluster.plone.org:
      ansible_user: root
      ansible_host: play3.playcluster.plone.org
      host: play3
      hostname: play3.playcluster.plone.org
      swarm_node:
        labels:
          type: worker
          env: production
          storage: persistent
  children:
    cluster_managers:
      children:
        cluster_manager:
          hosts:
            play1.playcluster.plone.org:

        cluster_managers_additional:
          hosts:

    cluster_workers:
      hosts:
        play2.playcluster.plone.org:
        play3.playcluster.plone.org:
standalone:
  hosts:
    play4.playcluster.plone.org:
      ansible_user: root
      ansible_host: play4.playcluster.plone.org
      host: play4
      hostname: play4.playcluster.plone.org
